<!--Реализуйте самостоятельно сохранение значений инпутов после отправки. Проверьте работу данного механизма.-->
<!--С помощью созданного класса сделайте форму с 5-ю инпутами. Пусть в каждый инпут можно ввести число.
Сделайте так, чтобы после отправки на экран выводилась сумма этих чисел, а введенные значения не пропадали из инпутов.-->

<?php
include 't10_finalClass.php';

class Form extends Tag
{
    public function __construct()
    {
        parent::__construct('form');
    }
}

class Input extends Tag
{
    public function __construct()
    {
        parent::__construct('input');
    }

    public function openTag()
    {
        $inputName = $this->getAttribute('name');
        if (isset($_REQUEST[$inputName]) && $this->getAttribute('name')) {
            $this->setAttribute('value', $_REQUEST[$inputName]);
        }
        return parent::openTag(); // TODO: Change the autogenerated stub
    }

    public function __toString()
    {
        return $this->openTag();
    }
}

$form = (new Form)->setAttributes(['action' => 'sum.php', 'method' => 'GET']);

echo $form->openTag();

echo (new Input)->setAttribute('name', 'num1');
echo (new Input)->setAttribute('name', 'num2');
echo (new Input)->setAttribute('name', 'num3');
echo (new Input)->setAttribute('name', 'num4');
echo (new Input)->setAttribute('name', 'num5');

echo (new Input)->setAttribute('type', 'submit');
echo $form->closeTag();


